### ISSUE TITLE
Can't compile server. Cannot find module 'pegjs'

### ISSUE THREAD

**Issue by ebugusey** [SrTobi/code-pegjs-language#1]
Tried to create `.vsix` package with `vsce package`. Got this error:

```
src/server.ts(10,24): error TS2307: Cannot find module 'pegjs'.
```

Package was created though. But when I'm installing it in vscode there is no language server in it, so no error detection for me.

But dependencies are installed in `./server` with `npm install`. And there is `pegjs` folder in `./server/node_modules`.

**Comment by ebugusey** [comment]
@SrTobi Do you have any information why this issue exists? Why `tsc` can't find this package?

**Comment by SrTobi** [comment]
Yeah: It's because the module typings are not present :smile:. As far as I am understanding it, tsc searches the typing files but it really searches for an ambient module. See [this](http://www.typescriptlang.org/Handbook#modules-working-with-other-javascript-libraries) for more information about ambient modules. The problem here is, that there is a file `pegjs.d.ts`, but it does not contain an ambient module `pegjs`. Rather it contains an ambient module `PEG`, which defines the stuff needed to use already compiled `.pegjs` files (especially the `parse(...)` function). Here the definition of the module `pegjs` with the function `buildParser(...)` is needed and there are no type definitions in https://github.com/DefinitelyTyped/DefinitelyTyped for `pegjs`.

**Comment by SrTobi** [comment]
I added typings in f1b43c4adecf13ce7639367bf6fda705a4dd1980 and added a pull request https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8356.
